api_platform:
    title: 'AppHotel'
    description: 'A Symfony API to manage hotel booking.'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
