vich_uploader:
    db_driver: orm

    mappings:
        room:
            uri_prefix: '%app.path.image%'
            upload_destination: '%kernel.project_dir%/upload%app.path.image%'
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\OrignameNamer
